import type { Property } from "./types"

export const properties: Property[] = [
  {
    name: "Quinta das Regadas",
    url: "quinta das regadas",
    price: 1767,
    pricePerPerson: 117.8,
    rooms: 7,
    features: {
      salaoJogos: false,
      piscinaExterior: true,
      piscinaInterior: false,
    },
    votes: {
      renato: "1º",
      carlos: "",
      cristovao: "x",
    },
  },
  {
    name: "Casa da Abuela",
    url: "casa da abuela",
    price: 1380,
    pricePerPerson: 92,
    rooms: 8,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: true,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Quinta do Raposinho",
    url: "quinta do raposinho",
    price: 1810,
    pricePerPerson: 120.67,
    rooms: 8,
    features: {
      salaoJogos: false,
      piscinaExterior: true,
      piscinaInterior: false,
    },
    votes: {
      renato: "3º",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Celorico Cottage",
    url: "celorico cottage",
    price: 1764,
    pricePerPerson: 117.6,
    rooms: 0,
    features: {
      salaoJogos: true,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "x",
    },
  },
  {
    name: "Casa do Cão Praia",
    url: "casa do cão praia",
    price: 1340,
    pricePerPerson: 89.33,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Cabanas",
    url: "cabanas",
    price: 1095,
    pricePerPerson: 73,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Douro Natura",
    url: "douro natura",
    price: 992,
    pricePerPerson: 66.13,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Casa de Plácios",
    url: "casa de plácios",
    price: 1245,
    pricePerPerson: 83,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Quinta da Moagem",
    url: "quinta da moagem",
    price: 1050,
    pricePerPerson: 70,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Uma Aldeia?",
    url: "uma aldeia?",
    price: 1556,
    pricePerPerson: 103.73,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Casa Paz",
    url: "casa paz",
    price: 1110,
    pricePerPerson: 74,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Quinta São Roque",
    url: "quinta são roque",
    price: 1725,
    pricePerPerson: 115,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Casa Rectoral",
    url: "casa rectoral",
    price: 1690,
    pricePerPerson: 112.67,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "x",
    },
  },
  {
    name: "Casa Assade",
    url: "casa assade",
    price: 1215,
    pricePerPerson: 81,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "2º",
      cristovao: "",
    },
  },
  {
    name: "Casa da Fonte",
    url: "casa da fonte",
    price: 1800,
    pricePerPerson: 120,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
  {
    name: "Casas da Azenha",
    url: "casas da azenha",
    price: 1311,
    pricePerPerson: 87.4,
    rooms: 0,
    features: {
      salaoJogos: false,
      piscinaExterior: false,
      piscinaInterior: false,
    },
    votes: {
      renato: "",
      carlos: "",
      cristovao: "",
    },
  },
]

